name: Trigger auto deployment for livenation-front-end

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/livenation-front-end-AutoDeployTrigger-ff24039e-a591-42ad-a3a9-b43cc4715531.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.LIVENATIONFRONTEND_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: livenation.azurecr.io
          registryUsername: ${{ secrets.LIVENATIONFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.LIVENATIONFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: livenation-front-end
          resourceGroup: rg-livenation
          imageToBuild: livenation.azurecr.io/livenation-front-end:${{ github.sha }}
          
            

     

